### ISSUE TITLE
如何进行地图事件支持

### ISSUE THREAD

**Issue by jurs30** [leftstick/BaiduMapForAngularJS#10]
地图选点，回调坐标,

**Comment by leftstick** [comment]
@jurs30 不好意思，目前由于我个人身体状况原因，没有这些功能的开发计划。当然，如果你能提供更全面的使用方式，可以方便我设计这些功能。也可能会在下一个版本支持此类功能。

亦或，你也可以通过`on-map-loaded="loadMap(map)"`事件拿到地图实例([文档](https://github.com/leftstick/BaiduMapForAngularJS/blob/master/docs/APIDocs.md#use-baidu-map-directive-in-the-template))，通过该`instance`你可以自己玩各种花样，不需要directive支持
