### ISSUE TITLE
is there a way to custom info window?

### ISSUE THREAD

**Issue by wesleywong** [leftstick/BaiduMapForAngularJS#11]
Hi, Is there a way i can custom the content inside infoWindow? I noticed infowindow currently in redrawMarkers function and assign specific content like:

`var msg = '<p>' + (marker.title || '') + '</p><p>' + (marker.content || '') + '</p>';`

I would like to add a button inside content and call other services, like modal popup. Is that possible i can inject a service (bootstrap modal) in your angular-baidu-map.js. or i can do it in html without modify your js

**Comment by leftstick** [comment]
currently there is no way to inject service for such purpose. Do what ever you need(hack html if it helps)

But i am thinking of a brand new version with more flexiable api
