### ISSUE TITLE
热力图这些如何添加？

### ISSUE THREAD

**Issue by corecible** [leftstick/BaiduMapForAngularJS#13]
热力图这些如何添加？
或这些如何添加到里面？
<script type="text/javascript">
	// 百度地图API功能
	var map = new BMap.Map("l-map");
	map.centerAndZoom(new BMap.Point(116.404, 39.915), 11);
	var walking = new BMap.WalkingRoute(map, {renderOptions: {map: map, panel: "r-result", autoViewport: true}});
	walking.search("天坛公园", "故宫");
</script>

**Comment by leftstick** [comment]
目前可以写在[loaded](https://leftstick.github.io/BaiduMapForAngularJS/#!/apidoc?api=baidu-map)事件里，如下：

```html
<baidu-map map-options="opts" loaded ="mapLoaded(map)"></baidu-map>
```

```javascript
app.controller('demoCtrl', ['$scope', function($scope) {
        $scope.opts = {
            centerAndZoom: {
                longitude: 116.403703,
                latitude: 39.920116,
                zoom: 16
            },
            enableKeyboard: true
        };

        $scope.mapLoaded = function(map) {
            var walking = new BMap.WalkingRoute(map, {renderOptions: {map: map, panel: "r-result", autoViewport: true}});
            walking.search("天坛公园", "故宫");
        };
    }
]);
```
