### ISSUE TITLE
IE11 "Promise" issue with BaiduMapForAngularJS

### ISSUE THREAD

**Issue by fanpengxin** [leftstick/BaiduMapForAngularJS#14]
I have got an issue when running app on IE 11 with BaiduMapForAngularJS. 
There are error message keeping popup  "Promise is undefined." and the controller method cannot be executed. 
Please help me to resolve it. Many thanks.

**Comment by leftstick** [comment]
The error is quite clear, `Promise is undefined`, it's known issue with IE11(not supporting `Promise`).
![screen shot 2017-05-10 at 10 26 40 am](https://cloud.githubusercontent.com/assets/1059956/25880636/3225feca-356b-11e7-8904-24b552b90945.png)




You can polyfill it as: [How to make promises work in IE11
](http://stackoverflow.com/questions/36016327/how-to-make-promises-work-in-ie11) described.

Or, add [es6-promise](https://github.com/stefanpenner/es6-promise) in your own way.
