### ISSUE TITLE
如何加载热力图呢

### ISSUE THREAD

**Issue by zhang6685979** [leftstick/BaiduMapForAngularJS#15]

**Comment by leftstick** [comment]
这个需要额外的插件，目前不支持，等我考虑下，看怎么在下个版本里想办法把API暴露出来吧。

**Comment by leftstick** [comment]
更新了`3.2.0`版本，增加了热力图支持：看[文档](https://leftstick.github.io/BaiduMapForAngularJS/#!/apidoc?api=overlay)
