### ISSUE TITLE
What should I do when it shows NO_NETWORK

### ISSUE THREAD

**Issue by mantinghui** [leftstick/BaiduMapForAngularJS#17]
It works well with “ionic serve” command on my PC，but shows NO_NETWORK on my android device.

**Comment by leftstick** [comment]
@mantinghui you are integrating it with your `ionic` app, right?

**Comment by mantinghui** [comment]
请问你可以说汉语的吗？可以的话，汉语交流吧？我确实是在ionic里使用的这个插件，ionic serve指令在浏览器运行很完美，但是打包APK到手机上就不行了。

**Comment by leftstick** [comment]
@mantinghui ，等我再发一版你试试

**Comment by leftstick** [comment]
@mantinghui 试试`3.2.2`吧，应该可以了

**Comment by mantinghui** [comment]
哦好的，我试一下
