### ISSUE TITLE
可以支持除热力图之外的图形么？

### ISSUE THREAD

**Issue by xiangyu1225** [leftstick/BaiduMapForAngularJS#18]
map.addOverlay(marker);            //增加点
map.addOverlay(polyline);          //增加折线
map.addOverlay(circle);            //增加圆
map.addOverlay(polygon);           //增加多边形
map.addOverlay(rectangle);         //增加矩形

**Comment by leftstick** [comment]
已增加，请试用`3.3.0`，[文档](https://leftstick.github.io/BaiduMapForAngularJS/#!/apidoc?api=polyline)

**Comment by xiangyu1225** [comment]
前段时间通过loaded获取的map实例也实现了，我用最新的再改一下，多谢！
