### ISSUE TITLE
地图用angular的视图切换一次就会显示不正常

### ISSUE THREAD

**Issue by MetSystem** [leftstick/BaiduMapForAngularJS#4]
地图用angular的视图切换一次就会显示不正常

**Comment by MetSystem** [comment]
![qq 20151224164344](https://cloud.githubusercontent.com/assets/7943054/11999892/fe43339a-ab03-11e5-8992-134d218a23e3.jpg)

**Comment by leftstick** [comment]
怎样的视图切换，是像例子里这样么？：[plunker](http://plnkr.co/edit/BIbtC0EZEp0g1HlNzTNK?p=preview)

**Comment by zhangna0922** [comment]
定位当前 位置 怎么写？

**Comment by leftstick** [comment]
@zhangna0922 目前不支持定位功能。

或者你可以给出期望的使用方法，我来更新组件？

**Comment by zhangna0922** [comment]
你可不可以  根据 HTML5 Geolocation API 定位用户的位置？

**Comment by leftstick** [comment]
可以，但需要你给出合适的use case。否则坐标是应该由使用者自行传入的，如下：

``` javascript
app.controller('demoCtrl', ['$scope',
    function($scope) {
        var longitude = 121.506191;
        var latitude = 31.245554;
        $scope.mapOptions = {
            center: {
                longitude: longitude,
                latitude: latitude
            }
        };
    }
]);
```

你可以自己获取当前坐标，然后传入`directive`，或者告诉我，你希望如何使用`directive`的自动定位功能？

**Comment by zuomoumou666** [comment]
请问如何解决没有网络会导致APP崩溃这件事

**Comment by leftstick** [comment]
没有网络为什么app会崩溃？你是什么样的app?

**Comment by zuomoumou666** [comment]
我刚学用ionic做了一个在百度地图上显示坐标位置进行监控的APP，不联网的时候这样显示
Uncaught ReferenceError: BMap is not defined baiduMap.js:241 
Error: [$injector:modulerr] Failed to instantiate module baiduMap due to:
Error: [$injector:nomod] Module 'baiduMap' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by leftstick** [comment]
了解了，如果你用`ionic`这种`hybrid`方案做mobile app的话，应该尝试用一些离线的地图插件，就不要用这个网页版了，我在这个插件里，确实没有考虑离线的问题。

或者你有什么想法，我们一起讨论下

**Comment by leftstick** [comment]
@zuomoumou666  正好儿这几天有点空，我做了全面重构`2.0.1`，以下几个特性：
1. 不需要自己手动在html里加`<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak={ak}"></script>`了，增加程序灵活性
2. 增加离线友好，现在没网络的时候，会显示一个灰色的框，里面写着`OFFLINE`，当你网络联通后，地图会自动刷出来，当然检测网络是否存在是有时间间隔的，默认是30s检查一次。当然你可以自己改短一点。看新的API就可以。

**Comment by zuomoumou666** [comment]
@leftstick 多谢你这么热心回答我的问题，谢谢
