### ISSUE TITLE
添加点击地图增加marker功能

### ISSUE THREAD

**Issue by zuomoumou666** [leftstick/BaiduMapForAngularJS#5]
您好，我的APP需要有一个点击地图，添加marker，最后把marker的坐标和地址作为一个数组传给controller的功能，在上一个版本上我 已经写好了一个简单的，但是新版本有些不明白，想请问，要扩展地图功能增加在哪里比较好，不会影响其他地方。

**Comment by leftstick** [comment]
如果之前版本就可以用的，那新版应该也可以，代码都不用变啊。你的问题是什么？

**Comment by zuomoumou666** [comment]
@leftstick 
之前是我自己添加的，改版后的代码有点不明白，所有才来提问在哪添加这个功能。
在options里增加一个参数，如果是true就开启一个功能。
功能为：点击地图，在地图上添加一个marker，点击这个marker，就删除他，最后把所有的marker的坐标和地址储存在一个数组里。我在用$http把这个数组发给服务器存起来。

**Comment by leftstick** [comment]
你这个基本属于业务需求，我这个是通用组件，基本不太可能为你这个需求单独做一个flag，那样对其它用户太不公平，他们并不需要这个功能。
我有下面两个思考：
1. 我需要一些时间思考，你这个需求是否能够抽象出来通用的部分(但这个就没具体时间点了，有时间我才能看)
2. 你从我这fork一遍项目，改我的源码。然后你的项目里就直接依赖你自己的fork好了。不要依赖npm我这个官方版本
