### ISSUE TITLE
请问，怎样才能将这个map实例导出来？

### ISSUE THREAD

**Issue by annilq** [leftstick/BaiduMapForAngularJS#6]
请问，怎样才能将这个map实例导出来？
有一些方法不能全部在指令中写，想把实例导出来在controller使用，但是我自己在指令中的scope对象指定双向绑定时候是无效的，请问要怎样绑定才能把实例导出来呢？

**Comment by leftstick** [comment]
首先，`directive`在`angular1`里的表现，某种意义上说，他就是`component`(组件)。组件即一个自包含的生态，外部调用方不应该想知道任何她内部的状态。所以试图通过`directive`获取实例不是一个好的思路。
既然你fork了这个项目，想必你应该有些特殊需求需要这个`directive`完成，那应该想办法扩展这个组件的能力，使之能够适应你的需求，而不是从外部获取实例。

当然，因为地图组件的特殊性，如果你强烈要求获取地图实例，也不是不可能，我可以提供一个回调函数，把实例返回给你

**Comment by annilq** [comment]
我看了下整个这个小项目代码写的结构很简洁，可能主要应该是用来展示的，所以没有暴露出什么东西，因为我这边需要有一些操作功能比如搜索什么的，所以希望有个实例返回，不过说来也奇怪，我fork了这个项目尝试着将实例导出却总是undefined，不知道是和webpack打包出来有影响吗，如果有时间还希望能不影响原功能前提下加个选项能导出实例最好，或者我参考你的思路再试试看，谢谢

**Comment by leftstick** [comment]
正好今天晚上有空，已经提供了这个功能，参考2.1.0吧，我新增了一个on-map-loaded回调选项，可以让你拿到地图实例

**Comment by annilq** [comment]
好咧，谢谢
