### ISSUE TITLE
离线显示离线信息以及BMap

### ISSUE THREAD

**Issue by chenliyu** [leftstick/BaiduMapForAngularJS#7]
Hello,
我使用您的指令，其他功能都正常，就是在离线状态下不能显示出离线信息——实际上在离线状态下页面啥都没有;另外，在你新版代码里，如果我想在地图里加入控件，有没有类似于BMap这样的角色存在？

**Comment by leftstick** [comment]
离线状态最初是为以下场景设计的：
- Hybrid app(如：cordova)开发时，已经将前端资源打包进app中，如果用户打开应用，但却没有开启网络，这时候会有离线信息提示

换句话说，只有当百度地图脚本`http://api.map.baidu.com/api?v=2.0`本身下载失败时(其他资源下载成功)才能提示出来，否则是没效果的。相信这个还是比较好理解的，一段脚本的生效必须建立在已经下载到客户端这个基础之上。

第二个问题，如果你想在组件中自己获取`BMap`实例做点什么其他事情，你可以参考[Use baidu-map directive in the template](https://github.com/leftstick/BaiduMapForAngularJS/blob/master/docs/APIDocs.md#use-baidu-map-directive-in-the-template)，里的`on-map-loaded`属性，里面传入回调函数，我会在`BMap`实例创建好之后通过这个回调函数传给你
