### ISSUE TITLE
factory(required（‘angular’）)无法运行

### ISSUE THREAD

**Issue by qiaoqiao1994** [leftstick/BaiduMapForAngularJS#8]
你好，我使用npm 下载后，需要将factory(required（‘angular’）)改为factory(angular)才能使用，请问这是什么问题？;

**Comment by leftstick** [comment]
你的`angular`是通过`<script>`标签直接加在`html`里的吧？

至于为什么会走的`typeof exports === 'object' && typeof module === 'object'`这个逻辑里，那你得看看自己的代码环境了。理论上如果你没有使用`browserify`或者`webpack`之类的打包工具，是不应该走到这个逻辑里的
